name: clone_api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/api" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@v0.1.4
      env:
          HOST: ${{ vars.SSH_HOST }}
          USERNAME: ${{ vars.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
      with:
          source: "."
          target: "/home/lenuage/www/gameshell.org/gameshell"
          
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          git clone git@github.com:mgloc/GameShell.git
