name: GameShell CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the GameShell repo
        uses: actions/checkout@v2
      - if: ${{ matrix.platform == 'ubuntu-latest' }}
        name: Install Linux deps
        run: |
          sudo apt install gettext-base python3 man-db psmisc nano tree bsdmainutils
      # - if: ${{ matrix.platform == 'macos-latest' }}
      #   name: Install macOS deps
      #   run: |
      #     brew install coreutils pstree tree man-db
      - name: Run the tests
        run: |
          # echo 'gsh systemconfig; for _ in $(seq 42); do gsh auto --abort; done; gsh index|cat' | ./start.sh -RDq
          echo 'gsh goto 26; for _ in $(seq 4); do gsh auto --abort; done; gsh index|cat' | ./start.sh -RDq
